---
- name: Create Plex dirs
  ansible.builtin.file:
    path: "{{ dir }}"
    state: directory
    owner: "{{ media_user }}"
    group: "{{ media_user }}"
    mode: "0750"
  loop:
    - "{{ docker_config_root }}/plexmediaserver"
    - "{{ zfs_pool_mount }}/tv"
    - "{{ zfs_pool_mount }}/movies"
  loop_control:
    loop_var: dir

- name: Create Plex container
  community.docker.docker_container:
    name: plexmediaserver
    image: lscr.io/linuxserver/plex:latest
    pull: always
    state: started
    restart_policy: unless-stopped
    network_mode: host
    env:
      PUID: "{{ media_uid }}"
      PGID: "{{ media_gid }}"
      TZ: "{{ timezone }}"
      VERSION: latest
    volumes:
      - "{{ docker_config_root }}/plexmediaserver:/config"
      - "{{ zfs_pool_mount }}/tv:/tv"
      - "{{ zfs_pool_mount }}/movies:/movies"
    devices:
      - /dev/dri:/dev/dri
