---
- name: Create Sonarr dir
  ansible.builtin.file:
    path: "{{ docker_config_root }}/sonarr"
    state: directory
    owner: "{{ media_user }}"
    group: "{{ media_user }}"
    mode: "0750"

- name: Create Sonarr container
  community.docker.docker_container:
    name: sonarr
    image: lscr.io/linuxserver/sonarr:latest
    pull: always
    state: started
    restart_policy: unless-stopped
    ports:
      - 8989:8989
    env:
      PUID: "{{ media_uid }}"
      PGID: "{{ media_gid }}"
      TZ: "{{ timezone }}"
    volumes:
      - "{{ docker_config_root }}/sonarr:/config"
      - "{{ zfs_pool_mount }}/downloads:/downloads"
      - "{{ zfs_pool_mount }}/tv:/tv"
