---
- name: Create Radarr dir
  ansible.builtin.file:
    path: "{{ docker_config_root }}/radarr"
    state: directory
    owner: "{{ media_user }}"
    group: "{{ media_user }}"
    mode: "0750"

- name: Create Radarr container
  community.docker.docker_container:
    name: radarr
    image: lscr.io/linuxserver/radarr:latest
    pull: always
    state: started
    restart_policy: unless-stopped
    ports:
      - 7878:7878
    env:
      PUID: "{{ media_uid }}"
      PGID: "{{ media_gid }}"
      TZ: "{{ timezone }}"
    volumes:
      - "{{ docker_config_root }}/radarr:/config"
      - "{{ zfs_pool_mount }}/downloads:/downloads"
      - "{{ zfs_pool_mount }}/movies:/movies"
