---
- name: Setup phthalo
  hosts: phthalo
  become: true

  tasks:
    - name: Create required users
      ansible.builtin.include_tasks: tasks/01-users.yml

    - name: Configure storage
      ansible.builtin.include_tasks: tasks/02-storage.yml

    - name: Install Docker
      ansible.builtin.include_tasks: tasks/03-docker.yml

    - name: Get media user
      ansible.builtin.getent:
        database: passwd
        key: "{{ media_user }}"

    - name: Set facts for Docker installation
      ansible.builtin.set_fact:
        media_uid: "{{ getent_passwd[media_user].1 }}"
        media_gid: "{{ getent_passwd[media_user].2 }}"

    - name: Setup Docker containers
      ansible.builtin.include_tasks: "{{ item }}"
      loop: "{{ lookup('fileglob', 'tasks/containers/*.yml', wantlist=True) }}"
