---
- name: Prepare hosts
  tags: init
  hosts: all
  become: true
  tasks:
    - name: Apt update
      ansible.builtin.apt:
        update_cache: true
        upgrade: dist
      when: ansible_distribution == "Debian"
  roles:
    - geerlingguy.security

- name: Set up Phthalo
  hosts: phthalo
  become: true
  vars:
    docker_users:
      - "{{ ansible_user }}"
  roles:
    - geerlingguy.docker
    - mrlesmithjr.zfs
  tags: init

- name: Deploy Unifi controller
  hosts: phthalo
  roles:
    - unifi
  tags: unifi

- name: Deploy media services
  hosts: phthalo
  become: true
  roles:
    - media
  tags: media-deploy
