---
- name: Create qBittorrent config dir
  ansible.builtin.file:
    path: "{{ media_user.home }}/.config/qbittorrent"
    state: directory
    owner: "{{ media_user.name }}"
    group: "{{ media_user.group }}"
    mode: "0750"
  register: qbt_config_dir

- name: Create qBittorrent downloads dir
  ansible.builtin.file:
    path: "{{ media_zfs_pool_mount }}/downloads/qbittorrent"
    state: directory
    owner: "{{ media_user.name }}"
    group: "{{ media_user.group }}"
    mode: "0770"

- name: Copy qBittorrent config file
  ansible.builtin.copy:
    src: qbittorrent.conf
    dest: "{{ qbt_config_dir.path }}/qBittorrent/qBittorrent.conf"
    owner: "{{ media_user.uid }}"
    group: "{{ media_user.group }}"
    mode: "0750"

- name: Create qBittorrent container
  community.docker.docker_container:
    name: qbittorrent
    image: lscr.io/linuxserver/qbittorrent:latest
    pull: always
    state: started
    restart_policy: unless-stopped
    networks:
      - name: phthalo-media
    env:
      PUID: "{{ media_user.uid }}"
      PGID: "{{ media_user.group }}"
      TZ: "{{ timezone }}"
      WEBUI_PORT: "8080"
      TORRENTING_PORT: "6881"
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    volumes:
      - "{{ qbt_config_dir.path }}:/config"
      - "{{ media_zfs_pool_mount }}:/data"
