---
- name: Create Sabnzbd user
  ansible.builtin.user:
    name: sabnzbd
    group: media
    password: "*"
  register: sab_user

- name: Create Sabnzbd dirs
  ansible.builtin.file:
    path: "{{ dir.name }}"
    state: directory
    owner: "{{ sab_user.name }}"
    group: media
    mode: "{{ dir.mode }}"
  loop:
    - name: "{{ sab_user.home }}/container_config"
      mode: "0750"
    - name: "{{ media_zfs_pool_mount }}/downloads/sabnzbd"
      mode: "0770"
    - name: "{{ media_zfs_pool_mount }}/downloads/sabnzbd/incomplete"
      mode: "0750"
    - name: "{{ media_zfs_pool_mount }}/downloads/sabnzbd/complete"
      mode: "0770"
  loop_control:
    loop_var: dir

- name: Copy Sabnzbd config file
  ansible.builtin.copy:
    src: sabnzbd.ini
    dest: "{{ sab_user.home }}/container_config/sabnzbd.ini"
    owner: "{{ sab_user.uid }}"
    group: "{{ sab_user.group }}"
    mode: "0750"

- name: Create Sabnzbd container
  community.docker.docker_container:
    name: sabnzbd
    image: lscr.io/linuxserver/sabnzbd:latest
    pull: always
    state: started
    restart_policy: unless-stopped
    env:
      PUID: "{{ sab_user.uid }}"
      PGID: "{{ sab_user.group }}"
      TZ: "{{ timezone }}"
    ports:
      - 8081:8081
    volumes:
      - "{{ sab_user.home }}/container_config:/config"
      - "{{ media_zfs_pool_mount }}/downloads:/downloads"
